### ISSUE TITLE
¿Sería posible añadir la puntuación en los resultados de la búsqueda?

### ISSUE THREAD

**Issue by dgongut** [Karmelo1984/api-filmaffinity#9]
Generalmente es algo que se suele poner junto al nombre y año de la película o serie.

Actualmente, para poder hacerlo tengo que recorrer la lista resultados y hacer un /api/film lo cual enlentece mucho la consulta.
Sería ideal que ese dato viniera directamente en la búsqueda ya que aparece en la página de búsqueda de Filmaffinity.

Enhorabuena por el proyecto, es de muchísima calidad.

**Comment by Karmelo1984** [comment]
Lo dejo como pendiente para las siguientes versiones. Ya que considero que es una mejora bastante interesante.

Resultado esperado:
```
[
   {
      "id": 267008,
      "title": "Star Wars. Episode I: The Phantom Menace",
      "year": 1999,
      "rating": 6.3,
      "votes": 103939,
      "link": "https://www.filmaffinity.com/en/film267008.html",
      "api": "http://localhost:3000/api/film?lang=en&id=267008"
   }
]
```

No sé el tiempo que tardaré en actualizarlo, ya que ahora mismo ando con otro proyecto entre manos.
